-- Seed experiences for Univers Performance & Libération
-- This script populates the experiences table with realistic training experiences
-- to be run AFTER universe.sql schema creation

INSERT INTO public.experiences (
  title, slug, category, kind,
  short_description, long_description,
  duration_minutes, audience, benefits, deliverables,
  format_details, is_active, featured, order_index
) VALUES
-- STRUCTURER (5 experiences)
(
  'Cartographier les processus critiques',
  'cartographier-processus-critiques',
  'STRUCTURER',
  'ATELIER',
  'Identifier et documenter les flux essentiels pour clarifier les rôles.',
  'Atelier collaboratif de structuration où l''équipe cartographie les processus clés de l''organisation, clarifie les responsabilités et identifie les points de friction.',
  180,
  ARRAY['Équipes de 8-25 personnes, tous niveaux'],
  ARRAY['Clarté des processus', 'Responsabilités définies', 'Efficacité accrue', 'Réduction du chaos'],
  ARRAY['Matrice de processus', 'Cartographie affichée', 'Documentation processus', 'Plan d''actions'],
  'En présentiel, travail en petits groupes puis restitution collective',
  true,
  true,
  1
),
(
  'Structurer les réunions pour retrouver du temps',
  'structurer-reunions',
  'STRUCTURER',
  'FORMATION',
  'Méthodes et outils pour des réunions efficaces et respectueuses du temps.',
  'Formation interactive sur les conditions d''une réunion efficace : cadrage, durée, participation, documentation. Pratiquer les techniques de facilitation.',
  120,
  ARRAY['Managers, coordinateurs, animateurs'],
  ARRAY['Réunions plus courtes', 'Meilleures décisions', 'Engagement renforcé', 'Temps récupéré'],
  ARRAY['Guide réunions efficaces', 'Modèles d''agenda', 'Checklist-test'],
  'En ligne ou présentiel, format mixte théorie/pratique',
  true,
  false,
  2
),
(
  'Déléguer sans surcharger : la responsabilité partagée',
  'deleguer-responsabilite-partagee',
  'STRUCTURER',
  'IMMERSION',
  'Journée d''accompagnement pour construire une culture de délégation.',
  'Immersion d''une journée complète : diagnostic des pratiques actuelles, ateliers sur la clarté des délégations, coaching d''équipe, mise en pratique immediate.',
  480,
  ARRAY['Équipes de 6-12, encadrement intermédiaire ou opérationnel'],
  ARRAY['Délégation fluide', 'Autonomie développée', 'Charge équilibrée', 'Apprentissage collectif'],
  ARRAY['Grille de compétences', 'Fiches de délégation', 'Plan de transfert'],
  'En présentiel sur une journée complète. Lunch inclus. Suivi 2 semaines après.',
  true,
  true,
  3
),
(
  'Rendre visible la charge mentale pour mieux l''organiser',
  'rendre-visible-charge-mentale',
  'STRUCTURER',
  'ATELIER',
  'Mesurer et cartographier la charge mentale comme point de départ de l''organisation.',
  'Atelier de sensibilisation et de travail collectif : qu''est-ce que la charge mentale, comment la mesurer, où intervenir en premier. Co-construction d''actions.',
  150,
  ARRAY['Tous niveaux, groupes de 10-30'],
  ARRAY['Compréhension partagée', 'Visibilité améliorée', 'Actions priorisées', 'Engagement renforcé'],
  ARRAY['Diagramme charge mentale équipe', 'Plan d''actions', 'Ressources'],
  'Atelier interactif, travail en sous-groupes puis restitution',
  true,
  false,
  4
),
(
  'Construire une gouvernance agile et légitime',
  'gouvernance-agile-legitime',
  'STRUCTURER',
  'FORMATION',
  'Fondamentaux d''une gouvernance moderne et adaptée au changement.',
  'Formation sur les bases de la gouvernance agile, les espaces décisionnels, la légitimité de l''information. Exemples concrets et adaptation à votre contexte.',
  240,
  ARRAY['Dirigeants, coordinateurs, maîtres d''ouvrage'],
  ARRAY['Gouvernance claire', 'Agilité organisationnelle', 'Légitimité du processus', 'Confiance accrue'],
  ARRAY['Charte gouvernance', 'Guide prise décision', 'Heatmap décisions'],
  'Formation en ligne ou présentiel, avec cas pratiques',
  true,
  false,
  5
),

-- LIBERER (5 experiences)
(
  'Transformer les conflits en créativité',
  'transformer-conflits-creativite',
  'LIBERER',
  'IMMERSION',
  'Trois jours d''apprentissage sur la médiation interne et la gestion constructive des tensions.',
  'Immersion de 3 jours pour acquérir les compétences de médiation : écoute active, reformulation, cadrage des tensions, créativité collective.',
  1440,
  ARRAY['RH, managers, facilitateurs internes, groupes 8-15'],
  ARRAY['Écoute amplifiée', 'Conflicts apaisés', 'Solutions créatives', 'Climat confiant'],
  ARRAY['Guide médiation', 'Fiches techniques', 'Ressources audio'],
  'En présentiel sur 3 jours. Petit groupe. Pratique intensive.',
  true,
  true,
  1
),
(
  'Entretiens touchant : oser l''authenticité au travail',
  'entretiens-authentiques',
  'LIBERER',
  'ATELIER',
  'Atelier sur l''écoute et les conversations réelles au travail.',
  'Petit groupe de travail sur les bases de la communication authentique : créer la sécurité psychologique, écouter sans juger, poser les questions qui libèrent.',
  120,
  ARRAY['Managers, leaders, tous qui animent des discussions'],
  ARRAY['Écoute améliorée', 'Confiance reconstituée', 'Clarté augmentée', 'Lien renforcé'],
  ARRAY['Guide entretien', 'Grille préparation', 'Ressource audio'],
  'Atelier en présentiel, petit groupe 6-10 personnes, beaucoup de pratique',
  true,
  true,
  2
),
(
  'Créer une culture d''appréciation et de reconnaissance',
  'culture-appreciation-reconnaissance',
  'LIBERER',
  'FORMATION',
  'Construire et pérenniser un climat de valorisation mutuelle.',
  'Formation sur les principes de l''appréciation au travail, les rituels de reconnaissance, la culture de la gratitude. Conception collaborative de vos rituels.',
  180,
  ARRAY['Managers, RH, leaders d''équipe, groupes 10-25'],
  ARRAY['Climat amélioré', 'Engagement renforcé', 'Turnover réduit', 'Fierté collective'],
  ARRAY['Kit rituels reconnaissance', 'Guide mise place', 'Cartes gratitude'],
  'En ligne ou présentiel. Théorie + conception d''actions concrètes',
  true,
  false,
  3
),
(
  'Apaiser les relations difficiles grâce à la compréhension mutuelle',
  'apaiser-relations-difficiles',
  'LIBERER',
  'ATELIER',
  'Reconnecter les équipes au-delà des malaises.',
  'Atelier spécialisé pour les équipes traversant des tensions : recréer le dialogue, comprendre chacun, retrouver le lien.',
  150,
  ARRAY['Équipes fragmentées, avec tension existante, 8-15 personnes'],
  ARRAY['Lien restauré', 'Communication rétablie', 'Malaise dissipé', 'Élan collectif'],
  ARRAY['Rapport diagnostic', 'Plan de reconnexion', 'Suivi 1 mois'],
  'Sur site, animé avec expertise haute en tensions intermépersonnelles',
  true,
  false,
  4
),
(
  'Rituels et micro-ajustements pour l''équilibre au quotidien',
  'rituels-micro-ajustements-equilibre',
  'LIBERER',
  'ATELIER',
  'Petites pratiques pour libérer la charge quotidienne.',
  'Atelier court mais dense : identifier nos rituels, créer les micro-ajustements, pratiquer ensemble. Objectif : implémenter en immédiat.',
  90,
  ARRAY['Tous niveaux, équipes de 6-20'],
  ARRAY['Charge mentale réduite', 'Équilibre retrouvé', 'Rituel ancré', 'Bien-être augmenté'],
  ARRAY['Rituel personnalisé equipe', 'Guide pratiques', 'Ressources'],
  'Atelier pouvant être fait sur lunch break ou pause.',
  true,
  true,
  5
),

-- RENFORCER (5 experiences)
(
  'Consolider la cohésion collective en change rapide',
  'cohesion-collective-changement',
  'RENFORCER',
  'IMMERSION',
  'Formation-action pour renforcer le lien lors de transformations.',
  'Immersion de 2 jours couplée à un accompagnement 3 mois : diagnostiquer la cohésion, construire ensemble une stratégie de renforcement, mettre en pratique.',
  960,
  ARRAY['Leadership collectif, équipes en transition, 12-30 personnes'],
  ARRAY['Cohésion amplifiée', 'Change porté collectivement', 'Résilience collective', 'Solidarité renforcée'],
  ARRAY['Cartographie cohesion', 'Plan actions 3 mois', 'Ressources renforcement'],
  'Immersion 2 jours + 3 mois suivi. Présentiel ou hybride.',
  true,
  true,
  1
),
(
  'Développer la résilience collective face aux crises',
  'resilience-collective-crises',
  'RENFORCER',
  'FORMATION',
  'Capacités collectives pour faire face et se rétablir rapidement.',
  'Formation sur les dimensions de la résilience collective : anticipation, adaptation, apprentissage. Cas étude et simulation.',
  210,
  ARRAY['Managers, coordinateurs, groupes de crise, 8-20 personnes'],
  ARRAY['Résilience augmentée', 'Agilité collective', 'Apprentissage rapide', 'Rétablissement plus fluide'],
  ARRAY['Guide résilience', 'Matrice anticipation', 'Checklist'],
  'En ligne ou présentiel, format participatif',
  true,
  false,
  2
),
(
  'Préparer la croissance et l''évolution organisationnelle',
  'preparer-croissance-evolution',
  'RENFORCER',
  'ATELIER',
  'Ateliers de planification pour structurer la croissance.',
  'Ateliers collectifs pour projeter la croissance : compétences à développer, structure à imaginero, capacités à construire, culture à pérenniser.',
  360,
  ARRAY['Leadership, managers clés, groupes 10-25'],
  ARRAY['Croissance préparée', 'Compétences anticipées', 'Culture renforcée', 'Scalabilité assurée'],
  ARRAY['Feuille de route croissance', 'Plan développement talents', 'Charte culture'],
  'Ateliers successifs sur 2-3 mois. Présentiel et online.',
  true,
  false,
  3
),
(
  'Créer une culture apprenante et innovante',
  'culture-apprenante-innovante',
  'RENFORCER',
  'FORMATION',
  'Construire un cadre où l''expérimentation et l''apprentissage deviennent la norme.',
  'Formation-atelier sur les principes de l''organisation apprenante : boucles de feedback rapides, expérimentation encouragée, apprentissage partagé. Conception vos mécanismes.',
  240,
  ARRAY['Leadership, managers, groupes pilotes, 12-30 personnes'],
  ARRAY['Culture apprenante établie', 'Innovation accélérée', 'Engagement augmenté', 'Performance collective'],
  ARRAY['Charte apprentissage', 'Kit expérimentation', 'Ressources'],
  'Mixte: formation + ateliers de co-design sur 2 mois',
  true,
  true,
  4
),
(
  'Construire une vision partagée et mobilisante',
  'vision-partagee-mobilisante',
  'RENFORCER',
  'ATELIER',
  'Co-créer une vision qui connecte et inspire.',
  'Atelier collectif de co-création : remonter nos forces, définir la direction, expliciter notre contribution, définir les jalons. Vision créée ensemble, portée ensemble.',
  180,
  ARRAY['Leadership collectif et équipe, groupes 15-40'],
  ARRAY['Vision partagée', 'Alignement augmenté', 'Mobilisation collective', 'Direction clarifiée'],
  ARRAY['Charte vision', 'Plan communication', 'Roadmap 3 ans'],
  'Atelier sur 1-2 jours ou plusieurs sessions étalées',
  true,
  true,
  5
)
ON CONFLICT DO NOTHING;

-- Verify insertion
SELECT COUNT(*) as total_experiences FROM public.experiences;
